- name: Ensure dotfiles are up to date.
  git:
    repo: "{{ config.dotfiles_repo }}"
    dest: "{{ config.dotfiles_dir }}"
    update: true

- name: Ensure secrets directory exists.
  file:
    dest: "{{ config.secrets_dir }}"
    state: directory

- name: Ensure secrets file is placed in the correct location.
  copy:
    dest: "{{ config.secrets_dir }}/secrets.json"
    content: "{{ secrets.secrets_file_contents | to_json }}"

- name: Find all GNU Stow directories.
  find:
    name: "{{ config.dotfiles_dir }}/"
    recurse: false
    file_type: directory
  register: stow_dirs

- name: Stow all found dotfile packages.
  shell:
    cmd: "stow -d {{ config.dotfiles_dir }} -t ~/ $(basename {{ item.path }})"
    chdir: "{{ config.dotfiles_dir }}"
  loop: "{{ stow_dirs.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Ensure oh-my-zsh is cloned
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "~/.oh-my-zsh"
    update: true
    depth: 1

- name: Ensure Powerlevel10k is cloned
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
    update: true

- name: Find all available wallpapers
  find:
    name: "~/.config/wallpapers/"
    recurse: true
    file_type: file
    patterns: '*.png,*.jpg,*.jpeg'
  register: wallpapers

- name: Set a random wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'{{ item.path }}'"
    state: present
  with_random_choice: "{{ wallpapers.files }}"
  loop_control:
    label: "{{ item.path }}"
  changed_when: False
